### ISSUE TITLE
Raspberi PI 2 B+

### ISSUE THREAD

**Issue by mathk** [rust-embedded/rust-raspi3-OS-tutorials#16]
Would that make sens to make this tutorial portable to older model like the raspi2 B+ ?

**Comment by andre-richter** [comment]
The tutorials have a rather strict dependency on the Arm v8 architecture, and this was intentional of me, because I wanted this to be a modern tutorial, featuring a modern 64bit CPU. However, there are in fact non-3 versions of the RPi that use this arch. The Pi would need to feature an Cortex-A53 SoC.

According to https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications, `RPi 2 Model B v1.2` should work therefore.

**Comment by andre-richter** [comment]
@mathk can we close this, is your question answered?
